name: Build nodeeditor

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  cmake-build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - qt_version: "5.15.2"
            modules: ""
            os: ubuntu-20.04
          - qt_version: "5.15.2"
            modules: ""
            os: windows-latest
          - qt_version: "5.15.2"
            modules: ""
            os: macos-latest

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.config.qt_version }}
          modules: ${{ matrix.config.modules }}

      # disable meanwhile, until I understand how to fix the install prefix with ninja
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup (Linux)
        if: startsWith (matrix.config.os, 'ubuntu')
        run: sudo apt-get install libxkbcommon-dev

      - name: Setup VS tools (Windows)
        if: startsWith (matrix.config.os, 'windows')
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Compile
        run: |
          cmake -S . -B cbuild -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_STATIC=ON
          cmake --build cbuild
          
      - name: Create App Image
        if: startsWith (matrix.config.os, 'ubuntu')
        run: |
           cmake --install cbuild --prefix=${{ github.workspace }}/cbuild/AppDir/usr/
           cd cbuild
           wget --no-verbose "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
           wget --no-verbose "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage"
           chmod +x linuxdeploy*.AppImage
           export OUTPUT=nodeeditor-x86_64.AppImage
           export LD_LIBRARY_PATH=AppDir/usr/lib/:$LD_LIBRARY_PATH
           export DEBUG=1
           ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage
      - name: Upload AppImage
        if: startsWith (matrix.config.os, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
           name: nodeeditor-Linux-Qt${{ matrix.config.qt_version }}-cmake-AppImage
           path: ${{ github.workspace }}/cbuild/nodeeditor-x86_64.AppImage
